const path = require('path');

function main(
  bucketName = 'my-bucket',
  filePath = path.join(__dirname, './resources', 'test.txt'),
  destFileName = 'file.txt',
  generationMatchPrecondition = 0
) {
  // [START storage_upload_file_with_contexts]
  const {Storage} = require('@google-cloud/storage');
  const storage = new Storage();

  async function uploadFileWithContexts() {
    const options = {
      destination: destFileName,
      preconditionOpts: {ifGenerationMatch: generationMatchPrecondition},
      // New Object Contexts Feature Logic
      metadata: {
        contexts: {
          custom: {
            department: {
              value: 'engineering',
            },
            environment: {
              value: 'production',
            },
          },
        },
      },
    };

    await storage.bucket(bucketName).upload(filePath, options);

    console.log(`${filePath} uploaded to ${bucketName} with custom contexts.`);
    console.log(
      'Note: createTime and updateTime will be generated by the server.'
    );
  }

  uploadFileWithContexts().catch(console.error);
  // [END storage_upload_file_with_contexts]
}

main(...process.argv.slice(2));
